
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class ChestCfg
{

	public Dictionary<string, ChestCfgImplement> chests{get;set;}

	public ChestCfg ()
	{
	}

	public ChestCfgImplement GetChestCfg(int chestId)
	{
		return chests[chestId.ToString()];
	}
}


public class ChestCfgImplement 
{
	public string Name {get; set;}
	public int[] FixItemIds {get; set;}
	public RandomItemChest RandomItem {get;set;}
	public string Icon { get; set;}
	public string Border { get; set;}

	public int GetChance(int randomChance)
	{
		int ret = 100-randomChance;
		return ret < 0? 0: ret;
	}
}

public class RandomItemChest 
{
	public int[] Ids{get; set;}
	public int[] Chance {get; set;}

	public int GetChance(ChestSource type)
	{
		int index = (int)type;
		if(index >= Chance.Length)
		{
			return 0;
		}else 
		{
			return Chance[index];
		}
	}
}

public enum ChestSource 
{
	FIRST_TIME = 0,
	FROM_GEM,
	NONE_GEM
}


