// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class ShopCfg
{
	public const int SHOP_ITEM_CHEST = 1000;
	public const int SHOP_ITEM_ENERGY = 2000;
	public const int SHOP_ITEM_GOLD = 3000;
	public const int SHOP_ITEM_GEM = 4000;
	public const int SHOP_ITEM_ITEM = 5000;
	public const int SHOP_ITEM_REVIVE = 6000;
	public const int SHOP_ITEM_BAG = 7000;
	public const int SHOP_ITEM_MOVE = 8000;
	public const int SHOP_ITEM_SET = 9000;

	public Dictionary<string, ShopItemCfg> chest {get;set;}
	public Dictionary<string, ShopItemCfg> energy {get;set;}
	public Dictionary<string, ShopItemCfg> gold {get;set;}
	public Dictionary<string, ShopItemCfg> gem {get;set;}
	public Dictionary<string, ShopItemCfg> item {get;set;}
	public Dictionary<string, ShopItemCfg> revive { get; set; }
	public Dictionary<string, ShopItemCfg> bag { get; set; }
	public Dictionary<string, ShopItemCfg> move { get; set; }
	public Dictionary<string, ShopItemCfg> set { get; set; }

	public ShopCfg ()
	{
	}
}

public class ShopItemCfg
{
	public int Id{get;set;}
	public int Type {get;set;}
	public string Name {get;set;}
	public string StoreId {get;set;}
	public string Description {get;set;}
	public int Quantity {get;set;}
	public int Gold {get;set;}
	public int Gem {get;set;}
	public double RM {get;set;} // real money
	public int Require {get;set;}

	public ShopItemCfg Clone()
	{
		ShopItemCfg item = new ShopItemCfg();
		item.Id = this.Id;
		item.Type = this.Type;
		item.Name = this.Name;
		item.StoreId = this.StoreId;
		item.Description = this.Description;
		item.Quantity = this.Quantity;
		item.Gold = this.Gold;
		item.Gem = this.Gem;
		item.RM = this.RM;
		item.Require = this.Require;
		return item;
	}
}