// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class AndroidNotifService : NotificationService
{
#if UNITY_ANDROID
	private AndroidJavaObject nativeObject = null;
#endif
	public AndroidNotifService ()
	{
	}

	public override void SendNotification (string name, string title, string body, int delay)
	{
#if UNITY_ANDROID
		if(nativeObject == null)
			nativeObject = new AndroidJavaObject("com.macaronics.notification.AlarmReceiver");
		nativeObject.CallStatic("startAlarm", new object[4]{body, "Heroes of Puzzle", body, delay});
#endif
	}
}


