// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

[RequireComponent(typeof(UISprite))]
public class NGUIAnimation : MonoBehaviour
{
	public string[] atlas;
	public int framerate = 20;
	public float interval = 10;
	public int loopTime = 2;
	private float timePerFrame ;
	private float dt;
	private UISprite sprite;
	private int index = 0;
	private float count;
	private int countLoop = 0;

	public NGUIAnimation ()
	{
	}

	void Awake() 
	{
		sprite = GetComponent<UISprite>();
		timePerFrame = 1f/ framerate;
		count = 0;
//		sprite.MakePixelPerfect();
	}

	void Update()
	{
		if(count > 0)
		{
			count -= Time.deltaTime;
		}else
		{
			dt += Time.deltaTime;
			if(dt > timePerFrame)
			{
				dt = 0;
				sprite.spriteName = atlas[index];
				index = ++index % atlas.Length;
				if(index == atlas.Length - 1)
				{
					++countLoop;
					if(countLoop == loopTime)
					{
						countLoop = 0;
						count = interval;
					}
				}
			}
		}
	}
}


