// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public class Stat
{
	public int hp{ get; set; }
	public int armor{ get; set; }
	public int damage{ get; set; }
	public int manaPool { get; set; }
	public int turn{ get; set; }	

	public int GetPoint()
	{
		return hp + armor * 4 + damage * 5;
	}
	
}


