// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

[Serializable]
public class ChestModel
{
	public List<ChestData> chests {get;set;}
	public List<int> openedChests {get;set;}

	public ChestModel ()
	{
	}

	public bool IsOpenedChest(int id)
	{
		return openedChests.Contains(id);
	}

	public ChestData OpenChest(int index)
	{
		if(index < chests.Count)
		{
			ChestData data =chests[index];
			chests.RemoveAt(index);
			if(IsOpenedChest(data.chestId))
			{
				openedChests.Add(data.chestId);
			}
			return data;
			
		}else
			return null;
	}

	public void AddChest(ChestData data, ChestSource source)
	{
		if(IsOpenedChest(data.chestId))
		{
			data.source = source;
		}else
		{
			data.source = ChestSource.FIRST_TIME;
		}
		chests.Add(data);
	}

}


