// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class InventoryModel
{
	public List<ItemBaseData> ListItemData { get; set; }
	public int MaxSlot {get;set;}
	public List<ItemBaseData> BuyBackListItem {get;set;}

	public InventoryModel ()
	{
		ListItemData = new List<ItemBaseData>();
		BuyBackListItem = new List<ItemBaseData>();
	}

	public bool AddItem(ItemBaseData item)
	{
		ListItemData.Add(item);
		return false;
	}

	public void InsertItemToFirst(ItemBaseData item)
	{
		ListItemData.Insert (0, item);
	}

	public bool RemoveItem(ItemBaseData item)
	{
		return ListItemData.Remove(item);
	}

	public bool AddBBItem(ItemBaseData item, int maxSlot)
	{
		if(BuyBackListItem.Count == maxSlot)
		{
			BuyBackListItem.RemoveAt(maxSlot - 1);
		}
		BuyBackListItem.Insert(0, item);
		return true;
	}

	public bool RemoveBBItem(ItemBaseData item)
	{
		return BuyBackListItem.Remove(item);
	}

	public void IncreaseMaxSlot(int num)
	{
		if(num > 0)
		{
			MaxSlot += num;
		}
	}

	public bool IsFull()
	{
		return MaxSlot <= ListItemData.Count;
	}


}


