// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

[Serializable]
public class PaymentModel
{
	public List<string> completedTransactionIds = new List<string>();
	public Dictionary<string,string> pendingTransactionIds = new Dictionary<string, string>();
	public PaymentModel ()
	{
	}

	public bool AddPendingTransaction(string tranId, string encodedTranId)
	{
		if(!HasTransaction(tranId))
		{
			pendingTransactionIds[tranId] = encodedTranId;
			return true;
		}
		return false;
	}

	public void RemovePendingTransaction(string tranId)
	{
		if(pendingTransactionIds.ContainsKey(tranId))
		{
			pendingTransactionIds.Remove(tranId);
		}
	}

	public bool CompleteTransaction(string tranId)
	{
		if(pendingTransactionIds.ContainsKey(tranId) && !completedTransactionIds.Contains(tranId))
		{
			pendingTransactionIds.Remove(tranId);
			completedTransactionIds.Add(tranId);
			return true;
		}
		return false;
	}

	public bool HasTransaction(string tranId)
	{
		return completedTransactionIds.Contains(tranId) || pendingTransactionIds.ContainsKey(tranId);
	}
}


