// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public enum ErrorCode
{
	UNKNOWN_ERROR = -1,
	OK,
	NOT_ENOUGH_GEM,
	NOT_ENOUGH_GOLD,
	NOT_ENOUGH_WEIGHT,
	NOT_ENOUGH_SLOT,
	NOT_ENOUGH_ENERGY,
	NOT_UNLOCK,
	UNKNOWN_ITEM,
	ITEM_MAX_LEVEL,
	ITEM_UPGRADE_FAIL,
	WAITING_FOR_PROCESS,
	NOT_WEAR_WEAPON,
	NOT_WEAR_ARMOR,
	NOT_WEAR_SHIELD
}

public enum PaymentErrorCode
{
	OK = 0,
 	PurchaseNetworkError,
	PurchaseDuplicateTransactionId,
	PurchaseFailedEvent,
	PurchaseCancelledEvent,
	PurchaseErrorPayload
}


